---

language: python
sudo: required
dist: trusty
python:
  - 2.7
before_install: # set up the machine
  - sudo apt-get update -qq
  - sudo apt-get install -qq ansible
install: # set up the environment
  - sudo ansible-playbook -i ansible/inventory/localhost.ini ansible/dev.yml
script: # run the tests
  - export SPARK_HOME=$(echo ~/spark-*)
  - export PYSPARK_PYTHON=~/miniconda2/bin/python
  - ./run-tests.sh
